version: '3'
services:
  dynamo:
    image: amazon/dynamodb-local:1.11.477
    ports:
      - 8000:8000
    command: -jar DynamoDBLocal.jar -sharedDb
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    depends_on:
      - dynamo
    environment:
      AWS_DYNAMO_URL: http://dynamo:8000
      AWS_ACCESS_KEY_ID: 1
      AWS_SECRET_ACCESS_KEY: 2
    ports:
      - 9000:9000
    entrypoint:
      - /app/bootstrap-app.sh
